-   type: EuRoC_NoIMU
    name: MH01
    args:
        root: /data/euroc_mav/mh01
        gt_pose: true
-   type: EuRoC_NoIMU
    name: MH02
    args:
        root: /data/euroc_mav/mh02
        gt_pose: true
-   type: EuRoC_NoIMU
    name: MH03
    args:
        root: /data/euroc_mav/mh03
        gt_pose: true
-   type: EuRoC_NoIMU
    name: MH04
    args:
        root: /data/euroc_mav/mh04
        gt_pose: true
-   type: EuRoC_NoIMU
    name: MH05
    args:
        root: /data/euroc_mav/mh05
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V101
    args:
        root: /data/euroc_mav/v101
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V102
    args:
        root: /data/euroc_mav/v102
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V103
    args:
        root: /data/euroc_mav/v103
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V201
    args:
        root: /data/euroc_mav/v201
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V202
    args:
        root: /data/euroc_mav/v202
        gt_pose: true
-   type: EuRoC_NoIMU
    name: V203
    args:
        root: /data/euroc_mav/v203
        gt_pose: true
